project:
  type: website
  output-dir: docs

website:
  title: "Population Dynamics Report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_description.qmd
        text: Data Description
      - href: data_analysis.qmd
        text: Data Analysis
      - href: results_discussion.qmd
        text: Results and Discussion
      - href: conclusion_further_reading.qmd
        text: Conclusion
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



