---
title: "Results and Discussion"
---

# Life Expectancy, Adolescent Fertility, and Under-5 Mortality Discussion

To begin discussing results, we'll start by reviewing all three indicators over time. The following is an interactive bubble chart with under-5 mortality rate on the x-axis, adolescent fertility rate on the y-axis, and life expectancy as bubble size. Each bubble represents a different country. (Note that life expectancy has been normalized in order to better visualize the change from 2000 - 2023. Also, 0.01 was added after this normalization in order to avoid a minimum of 0 years). Our goal in creating this bubble chart is to better visualize the trends and comparisons we discussed throughout our analysis.

As we progress through time, we see the general trend of increasing life expectancy (the bubble grows larger) and decreasing adolescent fertility as well as under-5 mortality (the bubbles move toward the origin of the graph). This, we saw too in our analyses of our three indicators in the indicator-over-time plots in the [data analysis](data_analysis.qmd) section. Thus, **we see a global improvement for all countries in terms of our indicators.**

```{python}
#| echo: true
#| eval: true
#| code-fold: true

# We will use pandas and plotly for this figure.
import pandas as pd
import plotly.express as px

# Read the dataset.
df = pd.read_csv('population_dynamics_clean.csv')

# Normalize the life expectancy column to see clearer changes
# 0.01 is added to avoid a minimum value of 0
df['life_expectancy_norm'] = 0.01 + (df['life_expectancy'] - df['life_expectancy'].min()) / (df['life_expectancy'].max() - df['life_expectancy'].min())

# Create an animated scatter plot/bubble chart
fig = px.scatter(
    df,
    x = "under5_mortality",
    y = "adolescent_fertility",
    title = "Life Expectancy, Under-5 Mortality, and Adolescent Fertility Rate Over Time",
    size = 'life_expectancy_norm',
    color = 'country',
    color_discrete_map = {
        'Brazil': '#ff7f0e',
        'India': 'green',
        'Kenya': 'red',
        'United Kingdom': '#9467bd',
        'Afghanistan': '#1f77b4'
    },
    hover_name = 'country',
    size_max = 60,
    animation_frame = 'year',
    animation_group ='country',
    labels={
        "under5_mortality": "Under-5 Mortality Rate",
        "adolescent_fertility": "Adolescent Fertility Rate",
        "life_expectancy_norm": "Life Expectancy (Normalized)"
    }
)

fig.show()
```

Additionally, in our analysis, we looked at the averages of our indicators from 2017 to 2023, and noticed that a country's income-level is closely associated with its average indicator value. That is, **even though there have been overall improvements over time, lower life expectancy, higher adolescent fertility rates, and higher under-5 mortality rates are still closely associated with lower-income countries.**

Further, if we pause the bubble chart on 2023, we can see that the countries, while having improved quite a lot since 2000, still appear in order of income level on the x- and y-axes (all except for India's adolescent fertility rate, which is discussed below in @sec-limitations). In 2023, Afghanistan still hasn't reached an under-5 mortality rate lower than that of Brazil's in 2000, and Kenya has only made small improvements to life expectancy compared to other countries. **Although there has been improvement, a lot of this improvement has been slow and difficult; while high-income countries have consistently strong indicator levels, countries of lower incomes not only face weaker indicator levels, but also greater hardship in breaking existing structures and reaching the ideal.**

# Adolscent Fertility and Secondary School Enrollment {#sec-af-sse}

We also analyzed adolescent fertility and secondary school enrollment. As mentioned in our analysis, we selected India and the United Kingdom based on their income category designations. This is because a country's access to education generally correlates with their GNI, as more money can be invested in schools and teachers. On the other hand, greater access to education is known to improve a country's economy as well, by increasing human capital and innovation.

We found that **secondary school enrollment and adolescent fertility are inversely correlated.** As the former increases, the latter decreases. Access to education can potentially lead to lower adolescent fertility rates, but this is only possible through a high income level.

# Under-5 Mortality and Adolescent Fertility

Finally, we found a **strong positive correlation between under-5 mortality and adolescent fertility.**

Intuitively, the strong positive correlation we found makes sense, as adolescent fertility is associated with complications during childbirth, and adolescents tend to be less suitable caretakers due to a lack of money and resources. Complications during childbirth as well as inefficient infant care can lead to child mortality. Thus, seeing a decrease in adolescent fertility would also likely come with a decrease in under-5 mortality.

But we may also consider this correlation from an economic perspective. Lower-income countries may not have the money to provide good reproductive healthcare and suitable nutrition for infants and children, or the resources to build good education systems to discourage adolescent fertility.

# Limitations {#sec-limitations}

There are several limitations of this report that we will point out.

First, is India's adolescent-fertility rate improvement. In Figure 3 on the [Data Analysis page](data_analysis.qmd), India reaches an adolescent fertility rate comparable to that of the United Kingdom by 2023. This may be due to their increasing secondary-school enrollment rates, as discussed in @sec-af-sse. Other variables, such as access to contraceptives, may have an affect as well, and could be studied through additional research. However, there may also be potential limitations to data collection in countries with lower income, such as India. If less information is collected on the adolescent fertility rate, there may be potential innaccuracies in the data to keep in consideration.

Additionally, this report considered a wide variety of countries. These countries vary not only in income level, but also in infrastructure, systems of government, culture, stigmas, and more, which are beyond the scope of this study. While income level plays a role in a country's population dynamics, so too do many other factors that may be considered for further research opportunities.